describe("yoda-core init", function()
  local yoda

  before_each(function()
    package.loaded["yoda-core"] = nil
    yoda = require("yoda-core")
  end)

  describe("setup()", function()
    it("accepts nil options", function()
      assert.has_no.errors(function()
        yoda.setup()
      end)
    end)

    it("accepts empty options", function()
      assert.has_no.errors(function()
        yoda.setup({})
      end)
    end)

    it("accepts use_di option", function()
      assert.has_no.errors(function()
        yoda.setup({ use_di = true })
      end)
    end)

    it("accepts dependencies option", function()
      assert.has_no.errors(function()
        yoda.setup({
          use_di = true,
          dependencies = { plenary_path = true },
        })
      end)
    end)
  end)

  describe("cache()", function()
    it("creates cache instance", function()
      local cache = yoda.cache()
      assert.is_not_nil(cache)
      assert.is_function(cache.get)
      assert.is_function(cache.set)
    end)

    it("creates cache with custom TTL", function()
      local cache = yoda.cache({ ttl_ms = 5000 })
      cache:set("test", "value")
      assert.equals("value", cache:get("test"))
    end)
  end)

  describe("io()", function()
    it("returns io module in standard mode", function()
      yoda.setup({ use_di = false })
      local io = yoda.io()
      assert.is_not_nil(io)
      assert.is_function(io.is_file)
      assert.is_function(io.read_file)
    end)

    it("returns io instance in DI mode", function()
      yoda.setup({ use_di = true })
      local io = yoda.io()
      assert.is_not_nil(io)
      assert.is_function(io.is_file)
      assert.is_function(io.read_file)
    end)
  end)

  describe("platform()", function()
    it("returns platform module in standard mode", function()
      yoda.setup({ use_di = false })
      local platform = yoda.platform()
      assert.is_not_nil(platform)
      assert.is_function(platform.is_windows)
      assert.is_function(platform.get_platform)
    end)

    it("returns platform instance in DI mode", function()
      yoda.setup({ use_di = true })
      local platform = yoda.platform()
      assert.is_not_nil(platform)
      assert.is_function(platform.is_windows)
      assert.is_function(platform.get_platform)
    end)
  end)

  describe("string()", function()
    it("returns string module in standard mode", function()
      yoda.setup({ use_di = false })
      local str = yoda.string()
      assert.is_not_nil(str)
      assert.is_function(str.trim)
      assert.is_function(str.split)
    end)

    it("returns string instance in DI mode", function()
      yoda.setup({ use_di = true })
      local str = yoda.string()
      assert.is_not_nil(str)
      assert.is_function(str.trim)
      assert.is_function(str.split)
    end)
  end)

  describe("table()", function()
    it("returns table module in standard mode", function()
      yoda.setup({ use_di = false })
      local tbl = yoda.table()
      assert.is_not_nil(tbl)
      assert.is_function(tbl.merge)
      assert.is_function(tbl.deep_copy)
    end)

    it("returns table instance in DI mode", function()
      yoda.setup({ use_di = true })
      local tbl = yoda.table()
      assert.is_not_nil(tbl)
      assert.is_function(tbl.merge)
      assert.is_function(tbl.deep_copy)
    end)
  end)

  describe("integration", function()
    it("works with all modules together", function()
      yoda.setup()
      local cache = yoda.cache({ ttl_ms = 1000 })
      local io = yoda.io()
      local platform = yoda.platform()
      local str = yoda.string()
      local tbl = yoda.table()

      assert.is_not_nil(cache)
      assert.is_not_nil(io)
      assert.is_not_nil(platform)
      assert.is_not_nil(str)
      assert.is_not_nil(tbl)

      local test_str = "  hello  "
      local trimmed = str.trim(test_str)
      assert.equals("hello", trimmed)

      local test_tbl = { a = 1 }
      local merged = tbl.merge(test_tbl, { b = 2 })
      assert.equals(1, merged.a)
      assert.equals(2, merged.b)

      local plat = platform.get_platform()
      assert.is_string(plat)
    end)
  end)
end)
